version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--label-enable"
      - "--interval"
      - "30"
    restart: always
    networks:
      - lab-network
    hostname: watchtower

  app:
    image: ghcr.io/templight41/lab-automation-ansible:latest
    ports:
      - "8085:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/lab-automation
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - HOSTNAME=0.0.0.0
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    depends_on:
      - mongo
    networks:
      - lab-network
    hostname: lab-app
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - lab-network
    hostname: mongo
    restart: unless-stopped

networks:
  lab-network:
    driver: bridge
    # Remove the internal: true line to make the network accessible

volumes:
  mongo-data:
